In [2]:
import numpy as np
import pandas as pd

2 자유도 역기구학 풀이 완

In [16]:
import numpy as np

const_theta = 0.38264

s_k = np.sin(const_theta)
c_k = np.cos(const_theta)

#link
L_1 = 0.15222
L_2 = 0.12325

# input pose (x,y) 초기 위치 [0.18  -0.141 0.36]
x = s_k*L_1 + L_2/2
y = -c_k*L_1 - L_2/2

if np.sqrt(x**2 + y**2) >= L_1+L_2:
    theta_1  = np.arctan2(y,x) + pi/2 - const_theta
    theta_2 = -(pi/2 - const_theta )

elif ((x - s_k*L_1)**2 + (y + c_k*L_1)**2) <= L_2**2:
    theta_1 = 0
    theta_2 = np.arctan2(y + c_k*L_1, x - s_k*L_1)

else:
    # cal.. theta_2
    s_2 = (L_1**2 + L_2**2 - (x**2) - (y**2))/(2 * L_1 * L_2)
    c_2 = np.sqrt(1-s_2**2)

    theta_2 = np.arctan2(s_2,c_2) + const_theta

    #cal.. theta_1
    A = np.array([[c_2*y - s_2*x, s_2*y + c_2*x],
                [-(s_2*y + c_2*x), c_2*y - s_2*x]])

    B = np.array([L_2 - s_2*L_1, -c_2*L_1 ])

    sol =np.linalg.solve(A,B)

    theta_1 = np.arctan2(sol[0],sol[1]) - const_theta

print("theta_2 = ",theta_2,"[rad]", "->", theta_2*180/np.pi, "[degree]")
print("theta_1 = ",theta_1,"[rad]", "->", theta_1*180/np.pi, "[degree]")

theta_2 =  -0.7853981633974482 [rad] -> -44.99999999999999 [degree]
theta_1 =  0 [rad] -> 0.0 [degree]


In [13]:
x = 0.05
y = -0.141

const_theta = 0.38264

s_k = np.sin(const_theta)
c_k = np.cos(const_theta)

x = s_k + L_2/2
y = -c_k + L_2/2

#link
L_1 = 0.15222
L_2 = 0.12325

(x - s_k)**2 + (y + c_k)**2 <= L_2**2
    


True

In [4]:
import numpy as np

# 4x4 행렬 A 정의
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 1, 15, 16]])

# A의 역행렬 A_inv 구하기
A_inv = np.linalg.inv(A)

# 4x1 행렬 B 정의
B = np.array([[1],
              [2],
              [3],
              [4]])

# A_inv와 B의 행렬곱
result = np.dot(A_inv, B)

# 결과 출력
print("A의 역행렬:\n", A_inv)
print("A_inv와 B의 행렬곱 결과:\n", result)

A의 역행렬:
 [[ 1.40737488e+14 -2.81474977e+14  1.40737488e+14  7.39567606e-02]
 [-7.17975207e-02  6.19834711e-02  8.65185950e-02 -7.69230769e-02]
 [-4.22212465e+14  8.44424930e+14 -4.22212465e+14 -6.80241279e-02]
 [ 2.81474977e+14 -5.62949953e+14  2.81474977e+14  7.09904442e-02]]
A_inv와 B의 행렬곱 결과:
 [[ 1.40737488e+14 -2.81474977e+14  1.40737488e+14  7.39567606e-02]
 [-1.43595041e-01  1.23966942e-01  1.73037190e-01 -1.53846154e-01]
 [-1.26663740e+15  2.53327479e+15 -1.26663740e+15 -2.04072384e-01]
 [ 1.12589991e+15 -2.25179981e+15  1.12589991e+15  2.83961777e-01]]
